# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='token',
            field=models.CharField(default='token', max_length=200, unique=True, verbose_name='token'),
        ),
        migrations.AlterField(
            model_name='benefactorprofile',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default='مرد', max_length=3, verbose_name='gender\u200c'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(default='Tehran', max_length=100, verbose_name='location'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='status',
            field=models.CharField(choices=[('P', 'pending'), ('V', 'verified'), ('C', 'confirmed')], default='P', max_length=1, verbose_name='User status'),
        ),
    ]
