# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 06:14
from __future__ import unicode_literals

import apps.accounts.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_auto_20190212_2112'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='admin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField(choices=[(0, 'Saturday'), (1, 'Sunday'), (2, 'Monday'), (3, 'Tuesday'), (4, 'Wednesday'), (5, 'Thursday'), (6, 'Friday')], verbose_name='days in week')),
                ('start_time', models.IntegerField(validators=[apps.accounts.models.validate_time], verbose_name='times in day')),
            ],
        ),
        migrations.AlterField(
            model_name='benefactorprofile',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن'), ('اهمیتی ندارد', 'اهمیتی\u200c ندارد')], default='N', max_length=20, verbose_name='gender\u200c'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='city',
            field=models.CharField(max_length=100, verbose_name='location'),
        ),
        migrations.AddField(
            model_name='benefactorprofile',
            name='schedule',
            field=models.ManyToManyField(to='accounts.Schedule'),
        ),
    ]
