# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-03 14:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('in_progress', 'in progress'), ('done', 'done')], default='in_progress', max_length=20, verbose_name='status\u200c')),
                ('location', models.CharField(max_length=100, verbose_name='location')),
            ],
        ),
        migrations.CreateModel(
            name='FinancialProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Project')),
                ('name', models.CharField(max_length=100, verbose_name='financial project name\u200c')),
                ('deadline', models.DateTimeField(blank=True, null=True)),
                ('money_needed', models.IntegerField(verbose_name='money needed\u200c')),
                ('money_donated', models.IntegerField(verbose_name='money donated\u200c')),
                ('benefactors', models.ManyToManyField(to='accounts.BenefactorProfile')),
            ],
            bases=('project.project',),
        ),
        migrations.CreateModel(
            name='NonFinancialProject',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='project.Project')),
                ('gender', models.CharField(choices=[('male', 'male'), ('female', 'female'), ('not_important', 'not important')], default='not_important', max_length=20, verbose_name='gender\u200c')),
                ('age', models.IntegerField(blank=True, null=True, verbose_name='Age\u200c')),
                ('benefactor', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.BenefactorProfile')),
                ('need', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.BenefactorSkill')),
            ],
            bases=('project.project',),
        ),
        migrations.AddField(
            model_name='project',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.OrganizationProfile'),
        ),
    ]
