# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-12 21:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nonfinancialproject',
            name='gender',
            field=models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن'), ('اهمیتی ندارد', 'اهمیتی\u200c ندارد')], default='اهمیتی ندارد', max_length=20, verbose_name='gender\u200c'),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_started', 'not_started'), ('in_progress', 'in progress'), ('done', 'done')], default='not_started', max_length=20, verbose_name='status\u200c'),
        ),
    ]
