# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-04 14:47
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0002_auto_20190203_1550'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField(default=5, validators=[django.core.validators.MaxValueValidator(5), django.core.validators.MinValueValidator(1)])),
                ('feedback', models.CharField(blank=True, max_length=1000, null=True, verbose_name='feedback')),
                ('feeder', models.CharField(choices=[('benefactor', 'benefactor'), ('organization', 'organization')], default='organization', max_length=20, verbose_name='feeder\u200c')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.NonFinancialProject')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('not_started', 'not started'), ('in_progress', 'in progress'), ('done', 'done')], default='not_started', max_length=20, verbose_name='status\u200c'),
        ),
    ]
