# -*- coding: utf-8 -*-
# Generated by Django 1.11.17 on 2019-02-13 06:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20190213_0614'),
        ('project', '0002_auto_20190212_2112'),
    ]

    operations = [
        migrations.AddField(
            model_name='nonfinancialproject',
            name='schedule',
            field=models.ManyToManyField(to='accounts.Schedule'),
        ),
    ]
